### ISSUE TITLE
Cannot find red_data.zip in repo

### ISSUE THREAD

**Issue by comacke** [YasCoMa/predprin#2]
I could not find the file for the 3rd step of the Preparation in the Usage instructions which says to

`Uncompress rdf_data.zip`

I cannot find this file in the repo. Is there somewhere else this can be downloaded from? Or can it be added to this repo?

**Comment by YasCoMa** [comment]
This zipped file is very large (1.1Gb) I could not upload it to the repository, but i can send you upon email request.

**Comment by YasCoMa** [comment]
I just uploaded using git lfs, you can find it in the repository now.
